const AuditLog = require("../models/AuditLog");
const { buildSuspiciousMap } = require("../utils/suspiciousDetection");
const { notifyRoles } = require("../utils/notificationService");

function toMs(x) {
  const t = new Date(x || 0).getTime();
  return Number.isFinite(t) ? t : 0;
}

function inferSuspiciousType(reasons = []) {
  if (reasons.some(r => r.startsWith("Change after anchoring"))) return "Change after anchoring";
  if (reasons.some(r => r.startsWith("Status flip-flop"))) return "Status flip-flop";
  if (reasons.some(r => r.startsWith("Sensitive edits"))) return "Sensitive field edits";
  if (reasons.some(r => r.startsWith("Burst edits"))) return "Burst edits";
  if (reasons.some(r => r.startsWith("Login/Logout burst"))) return "Login/Logout burst";
  return "Suspicious activity";
}

async function runSuspiciousNotifyJob() {
  // Load recent logs (same as your admin page)
  const logs = await AuditLog.find({ action_type: { $ne: "DEMO_ACTION" } })
    .sort({ timestamp: -1 })
    .limit(3000)
    .lean();

  const suspiciousMap = buildSuspiciousMap(logs);

  // Build incidents (same grouping idea, simplified but safe)
  const incidents = [];

  for (const log of logs) {
    const flag = suspiciousMap[String(log._id)];
    if (!flag) continue;

    const reasons = flag.reasons || [];
    const timeMs = toMs(log.action_timestamp || log.timestamp);

    incidents.push({
      incidentId: `LOG::${String(log._id)}`,
      suspiciousType: inferSuspiciousType(reasons),
      type: "OTHER",
      user: log.username || "System",
      time: timeMs,
      entitySummary: String(log.entity_id || ""),
      severity: flag.severity || 1,
      reasons
    });
  }

  // Notify only meaningful severity, limit to avoid spam
  const top = incidents
    .filter(it => (it.severity || 1) >= 3)
    .sort((a, b) => b.time - a.time)
    .slice(0, 20);

  for (const it of top) {
    // Operations notification (no link)
    await notifyRoles(
      ["operations"],
      {
        category: "PROCESS_ALERT",
        severity: "warning",
        title: "Process anomaly detected",
        message: "System detected an anomaly in recent delivery handling.",
        data: {
          deliveryId: it.entitySummary || "",
          eventType: it.suspiciousType || it.type || "",
          timeWindow: "recent activity",
          suggestedAction: "Please ensure status updates reflect actual delivery outcomes."
        },
        link_url: "",
        dedupe_key: `OPS_ANOM::${it.incidentId}`
      },
      { dedupeMinutes: 60 }
    );

    // Admin notification (link to suspicious review)
    await notifyRoles(
      ["admin"],
      {
        category: "RISK_OVERSIGHT",
        severity: (it.severity || 1) >= 5 ? "critical" : "warning",
        title: "Suspicious activity detected",
        message: "A suspicious activity finding was generated by compliance rules.",
        data: {
          findingType: it.suspiciousType,
          severityScore: it.severity,
          userInvolved: it.user,
          entityId: it.entitySummary,
          reasons: it.reasons || [],
          action: "Open investigation / assign case note"
        },
        link_url: "/admin/review",
        dedupe_key: `ADMIN_ANOM::${it.incidentId}`
      },
      { dedupeMinutes: 60 }
    );
  }

  return { createdCandidates: top.length };
}

module.exports = { runSuspiciousNotifyJob };
